CREATE TABLE users (
  id INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
  name VARCHAR(63) NOT NULL,
  email VARCHAR(127) NOT NULL,
  password VARCHAR(127) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);